name: CI

on:
  push:
    branches:
    - master
    - develop
    - feature/*
  pull_request:
    branches:
    - develop

# macOS environments: https://github.com/actions/virtual-environments/tree/main/images/macos

jobs:
  build:
    name: CI build
    runs-on: macos-11
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: force Xcode 13.1
        run: sudo xcode-select -switch /Applications/Xcode_13.1.app
      - name: setup
        run: exec ./.github/scripts/setup.sh
      - name: build
        run: exec ./.github/scripts/build.sh
